# Generated by Django 3.2.15 on 2022-09-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0003_auto_20220913_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='User',
        ),
    ]
