# Generated by Django 3.2.15 on 2022-09-14 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0004_remove_userdetails_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Signup',
        ),
    ]
