# Generated by Django 3.2.15 on 2022-09-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0006_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
